### ISSUE TITLE
State-specific third dose data is missing since 23 Feb

### ISSUE THREAD

**Issue by Booligoosh** [jxeeno/aust-govt-covid19-vaccine-pdf#26]
Hi Ken, thanks for your amazing work!

It looks like since 23 Feb, all state-specific third dose data values eg. `AIR_NSW_18_PLUS_THIRD_DOSE_COUNT` appear to be missing from https://vaccinedata.covid19nearme.com.au/data/air.json

**Comment by nwbort** [comment]
Looks to align with changes to that slide on 25 Feb.

24 Feb slide:
![image](https://user-images.githubusercontent.com/30829548/155909661-e4a05a08-d5a6-49e4-8896-f80b954012ec.png)

25 Feb slide:
![image](https://user-images.githubusercontent.com/30829548/155909669-638a48d6-6c6d-43d9-8b57-424f02892e40.png)

**Comment by jxeeno** [comment]
Hey, thanks for reporting!

Yep, looks like it's due to the change in layout.  Have a bit of a busy week, but I'll try and get it fixed up as soon as possible

**Comment by jxeeno** [comment]
This should be fixed now :)

Note, yesterday's data is missing jurisdictional breakdown by age due to incorrect slide uploaded by DOH.  I'll contact them to get this resolved

**Comment by chrisjbillington** [comment]
I am still seeing the data missing for a single day, for example `2022-02-24` has no `AIR_NSW_18_PLUS_THIRD_DOSE_COUNT`. Is this unavoidable, or an off-by-one error in fixing this issue?

**Comment by jxeeno** [comment]
> I am still seeing the data missing for a single day, for example `2022-02-24` has no `AIR_NSW_18_PLUS_THIRD_DOSE_COUNT`. Is this unavoidable, or an off-by-one error in fixing this issue?

Looks like I hardcoded the wrong start date for the new layout.  Should be good now @chrisjbillington

**Comment by Booligoosh** [comment]
Thank you so much Ken, really appreciate it! ❤️
